### ISSUE TITLE
SyntaxError: non-default argument follows default argument

### ISSUE THREAD

**Issue by Heagan** [GypsyDangerous/simple-deep-neural-network#3]
consider changing:
def __init__(self, inputs, layers=1, hidden, output, epochs=10, learning_rate=.01, minibatch_size=1):
to:
def __init__(self, inputs, hidden, output, layers=1, epochs=10, learning_rate=.01, minibatch_size=1):

**Comment by GypsyDangerous** [comment]
Thanks, I made that change.
